- module-name: 'jwlcore'
  dlls:
    - filename:
        relative-path: 'libs'
        prefix: 'libjwlCore'
        suffix: 'so'
      when: 'linux'
    - filename:
        relative-path: 'libs'
        prefix: 'libjwlCore'
        suffix: 'dylib'
      when: 'macos'
    - filename:
        relative-path: '.'
        prefix: 'jwlCore-amd64'
        suffix: 'dll'
      when: 'win32'
    - filename:
        relative-path: '.'
        prefix: 'sqlite3_64'
        suffix: 'dll'
      when: 'win32'