# yamllint disable rule:line-length
# yamllint disable rule:indentation
# yamllint disable rule:comments-indentation

- module-name: 'jwlcore'
  dlls:
    - from-filenames:
        relative-path: 'libs'
        prefixes:
          - 'libjwlCore'
        suffixes:
          - 'so'
      when: 'linux'

    - from-filenames:
        relative-path: 'libs'
        prefixes:
          'libjwlCore'
        suffixes:
          - 'dylib'
      when: 'macos'

    - from-filenames:
        relative-path: '.'
        prefixes:
          - 'jwlCore-amd64'
          - 'sqlite3_64'
        suffixes:
          - 'dll'
      when: 'win32'
